# Generated by Django 4.1.4 on 2023-01-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_song_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
